### ISSUE TITLE
localStorage在hex中速度非常慢

### ISSUE THREAD

**Issue by as3long** [netease-youdao/hex#63]
localStorage在hex中速度非常慢。

**Comment by jacklcz** [comment]
正需要用

**Comment by bartonding** [comment]
我测试了下，速度和原生chrome没区别啊，不知道你是怎么得出这个结论的

下面是我的测试用例, chrome 32 正式版 300ms，30ms，hex_1.1.6_1621_windows32下 200ms，30ms. （数据都是近视值，虽然不太严格，但大体还是能体现，没发现你说的问题）

var sum = 10000;

var t1, t2;
t1 = +new Date;
for (var i = 0; i < sum; i ++) {
    localStorage.setItem('test' + i, i);
}
t2 = +new Date;
console.log('setItem.' + sum + ': ', t2 - t1);

t1 = +new Date;
for (var i = 0; i < sum; i ++) {
    localStorage.getItem('test' + i);
}
t2 = +new Date;
console.log('getItem.' + sum + ': ', t2 - t1);

**Comment by bartonding** [comment]
关于localStorage的性能，可以看看 http://www.stevesouders.com/blog/2014/02/11/measuring-localstorage-performance/ 这个文章

**Comment by as3long** [comment]
谢谢你的回复，我那天是直接将一个TODO的放在里面执行的时候发现有几秒钟左右的延迟。今天看到你的回复，我再测试了一下。非常流畅，没有问题。

**Comment by as3long** [comment]
谢谢你的回复，我那天是直接将一个TODO的放在里面执行的时候发现有几秒钟左右的延迟。今天看到你的回复，我再测试了一下。非常流畅，没有问题。
