### ISSUE TITLE
有关跨域安全问题

### ISSUE THREAD

**Issue by wildcatking** [netease-youdao/hex#66]
在Hex下跨域没任何问题，可是在hexium下，跨域会报错。不是说hexium用于调试开发Hex下的应用吗。特性都不一样咋调试

**Comment by bartonding** [comment]
hexium默认不开启，可通过新建一个快捷方式，然后修改目标为“D:...\hexium.exe --disable-web-security” 即可，注意带上参数 “--disable-web-security”

**Comment by wildcatking** [comment]
哦，多谢
