### ISSUE TITLE
设置icon_path不起作用，版本为最新版hex_1.1.9_1621_windows32

### ISSUE THREAD

**Issue by gzcz** [netease-youdao/hex#77]
设置icon_path不起作用，版本为最新版hex_1.1.9_1621_windows32 
![qq20140804104814](https://cloud.githubusercontent.com/assets/5310178/3792728/d1fc1f94-1b81-11e4-9078-321df6013253.jpg)
![qq20140804104925](https://cloud.githubusercontent.com/assets/5310178/3792737/0d5e7b7c-1b82-11e4-9df6-5a16ff5f96a2.jpg)

**Comment by bartonding** [comment]
暂不支持 $(AppDir) 表达式, 先用相对或绝对路径吧，下个版本中即可支持

**Comment by gzcz** [comment]
你的回信很及时，但没有解决我的问题，我使用了相对路径 "icon_path": "./logo.png" 或者 "icon_path": "logo.png" 也不行，我的logo.png图片和mainifest.json在同一目录，也就是应用程序的根目录。我应该怎么设置才可以？我很喜欢hex，这是我心中需要的软件。

**Comment by bartonding** [comment]
图标必须是 icon 格式（注意是格式，而不是png改成icon），否则window不认

**Comment by gzcz** [comment]
非常感谢你的回答，这是一个很棒的主意和想法hex，当然如果有hex on android更棒。我有一个前端的ui网页，http://www.yz6970.com/ios/  以前使用phonegap来打包，但phonegap让我很沮丧。很欣赏hex

**Comment by gzcz** [comment]
![qq20140804112043](https://cloud.githubusercontent.com/assets/5310178/3792885/6c4fd12c-1b86-11e4-8cc9-b99b5c314ee7.jpg)

**Comment by smallmacro** [comment]
已经验证，需要绝对或者相对路径,所用的图片格式必须是ico格式的。
